### ISSUE TITLE
Feature request: negative rank

### ISSUE THREAD

**Issue by kckennylau** [iatorm/jellyfish#2]
Positive ranks count the distance from the innermost item, then negative ranks should count the distance from the outermost item.

For example, [this](http://jellyfish.tryitonline.net/#code=cGAgLGkKIC0x&input=W1sxIDJdIFszIDRdIFs1IFs2IDddXV0) should give `[[1 2] [3 4] [5 6 7]]`.

**Comment by iatorm** [comment]
The language already supports negative levels, but level -1 corresponds to the entire input. Level -2 is the items, -3 is items of items, and so on. [This program](http://jellyfish.tryitonline.net/#code=cGAgLGkKIEYKIC0y&input=W1sxIDJdIFszIDRdIFs1IFs2IDddXV0) does what you're looking for. Note the `F`; it prevents ``` from handling `-` as a function argument.
